FROM node:20 AS build

WORKDIR /app
COPY ./backend/package*.json ./
RUN npm install --omit=dev
COPY ./backend .

RUN npm run build

FROM node:20-slim
WORKDIR /app
COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package*.json ./

CMD ["npm", "run", "start:prod"]
