services:
  db:
    image: postgres:16
    container_name: "terragrow-technicaltest-db-prod"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: erp
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    container_name: "terragrow-technicaltest-backend-prod"
    build:
      context: ../
      dockerfile: ./docker/backend/Dockerfile.prod
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/erp
    depends_on:
      - db

  frontend:
    container_name: "terragrow-technicaltest-frontend-prod"
    build:
      context: ../
      dockerfile: ./docker/frontend/Dockerfile.prod
    ports:
      - "127.0.0.1:4200:4200"
    depends_on:
      - backend
    restart: always

volumes:
  db-data:
